// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineBookStore.Models;

namespace OnlineBookStore.Migrations
{
    [DbContext(typeof(OnlineBookStoreDbContext))]
    partial class OnlineBookStoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineBookStore.Models.BookCategory", b =>
                {
                    b.Property<int>("bookCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("bookCategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("bookCategoryId");

                    b.ToTable("Tb_BookCategory");
                });

            modelBuilder.Entity("OnlineBookStore.Models.BookItem", b =>
                {
                    b.Property<int>("bookItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("bookCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("bookItemImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bookItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("creationalDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.Property<decimal>("purchasePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("salesPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("bookItemId");

                    b.HasIndex("bookCategoryId");

                    b.ToTable("Tb_BookItem");
                });

            modelBuilder.Entity("OnlineBookStore.Models.BookItemImage", b =>
                {
                    b.Property<int>("bookItemImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("bookImageName")
                        .HasColumnType("int");

                    b.Property<int>("bookItemId")
                        .HasColumnType("int");

                    b.HasKey("bookItemImageId");

                    b.HasIndex("bookItemId");

                    b.ToTable("BookItemImage");
                });

            modelBuilder.Entity("OnlineBookStore.Models.Discount", b =>
                {
                    b.Property<int>("discountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("bookItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("discountEndingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("discountName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("discountPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("discountStartingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("getdate()");

                    b.HasKey("discountId");

                    b.HasIndex("bookItemId");

                    b.ToTable("Tb_Discount");
                });

            modelBuilder.Entity("OnlineBookStore.Models.Slider", b =>
                {
                    b.Property<int>("sliderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("sliderDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sliderImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sliderTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sliderId");

                    b.ToTable("Slider");
                });

            modelBuilder.Entity("OnlineBookStore.Models.BookItem", b =>
                {
                    b.HasOne("OnlineBookStore.Models.BookCategory", "bookCategory")
                        .WithMany("bookItems")
                        .HasForeignKey("bookCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookStore.Models.BookItemImage", b =>
                {
                    b.HasOne("OnlineBookStore.Models.BookItem", "bookItem")
                        .WithMany("bookItemImageList")
                        .HasForeignKey("bookItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineBookStore.Models.Discount", b =>
                {
                    b.HasOne("OnlineBookStore.Models.BookItem", "bookItem")
                        .WithMany("discountList")
                        .HasForeignKey("bookItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
